sudo: required
services:
  - docker

before_install:
  - docker build -t nuge/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nuge/react-test npm test -- --coverage

after_success:
  - docker build -t nuge/multi-client ./client
  - docker build -t nuge/multi-nginx ./nginx
  - docker build -t nuge/mulit-server ./server
  - docker build -t nuge/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - dokcer push nuge/multi-client
  - dokcer push nuge/multi-nginx
  - dokcer push nuge/multi-server
  - dokcer push nuge/multi-worker